version: '3.9'

services:
  praksasch:
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    networks:
      - application
      - database
    ports:
      - "8081:8080"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: praksasch
    depends_on:
      - database

  database:
    image: postgres:13
    restart: always
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: praksasch
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./praksasch-init-data.sql:/tmp/praksasch-init.sql
    ports:
      - "5432:5432"

volumes:
  database-data:

networks:
  application:
  database:
